# Generated by Django 3.2.13 on 2023-06-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20230623_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllContents',
        ),
    ]
